name: 'YAML input action'
description: 'Process YAML and turn values into inputs'
inputs:
  yaml-file:
    description: 'Path to the YAML file'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
