name: Test YAML Input

on:
  workflow_dispatch:

jobs:
  run-yaml-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use my action
      uses: ./
      with:
        yaml-file: 'sample-input.yml'

    - name: Print ENV context
      run: |
        echo "${{toJSON(env)}}"
