name: Test YAML Input

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run-yaml-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use my action
      id: yaml-input
      uses: ./
      with:
        yaml-file: 'sample-input.yml'

    - name: Print ENV context
      env: 
        ENV_CONTEXT: ${{ toJson(env) }}
      run: |
        echo "$ENV_CONTEXT"

    - name: Print as Output
      run: echo "${{ steps.yaml-input.outputs.repo_name }}"

    outputs:
      my_repo_name: ${{ steps.yaml-input.outputs.repo_name }}

  second-job:
    runs-on: ubuntu-latest
    needs: run-yaml-input

    steps:
      - name: Get Env Vars
        id: get-env-vars
        run: echo ${{ needs.run-yaml-input.outputs.my_repo_name }}